-- /opt/eodi/mysql/init/00-init.sql

SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;
SET collation_connection = 'utf8mb4_unicode_ci';

CREATE DATABASE IF NOT EXISTS __MYSQL_DATABASE__
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS '__MYSQL_USER__'@'%'
IDENTIFIED BY '__MYSQL_PASSWORD__';

GRANT ALL PRIVILEGES ON __DB_NAME__.* TO '__MYSQL_USER__'@'%';
FLUSH PRIVILEGES;
